name: ModularGroup
version: 1.0.0
date: 2018-10-27
description: |
    Finite-index subgroups of (P)SL(2,Integers)

authors:
    - name: Luca Leon Junk
      url: http://www.math.uni-sb.de/ag/weitze/

maintainers:
    - name: Luca Leon Junk
      url: http://www.math.uni-sb.de/ag/weitze/

GAP: "4.5.3"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CTblLib"
      version: ">= 1.2.2"
      url: "http://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib"

suggested-pkgs:
    - name: "Congruence"
      version: ">=1.1.1"
      url: "http://www.cs.st-andrews.ac.uk/~alexk/congruence/"

www: https://github.com/le-on/ModularGroup
readme: README.md
packageinfo: https://github.com/le-on/ModularGroup/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/le-on/ModularGroup/releases/download/v1.0.0/ModularGroup-1.0.0.tar.gz

abstract: |
    This package provides a collection of algorithms for computing with   finit-index subgroups of (P)SL(2,Z).

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    PSL(2,Z), PSL2Z, SL(2,Z), SL2Z, modular group, congruence subgroup.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Jun18</span>]   <b class='BibAuthor'>Junk, L. L.</b>,
     <i class='BibTitle'>ModularGroup, Finite-index subgroups of (P)SL(2,Integers),
             Version 1.0.0</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/le-on/ModularGroup">https://github.com/le-on/ModularGroup</a></span>.
    </p>
    

bibtex: |
    @misc{ ModularGroup1.0.0,
      author =           {Junk, L. L.},
      title =            {{ModularGroup},      Finite-index     subgroups     of
                          (P)SL(2,Integers), {V}ersion 1.0.0},
      month =            {Oct},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href          {https://github.com/le-on/ModularGroup}
                          {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{le-on/}\discretionary
                          {}{}{}\texttt{ModularGroup}}},
      keywords =         {PSL(2,Z);   PSL2Z;   SL(2,Z);   SL2Z;  modular  group;
                          congruence subgroup},
      printedkey =       {Jun18}
    }

